- name: Create directory for apt keyrings
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"

- name: Download Docker GPG key
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: "0644"
  when: ansible_distribution == "Ubuntu"

- name: Download Docker GPG key
  get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: "0644"
  when: ansible_distribution == "Debian"

- name: Get DEB architecture
  shell: dpkg --print-architecture
  register: deb_architecture

- name: Add Docker repository to Apt sources
  lineinfile:
    path: /etc/apt/sources.list.d/docker.list
    line: "deb [arch={{ deb_architecture.stdout }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    create: yes
  when: ansible_distribution == "Ubuntu"

- name: Add Docker repository to Apt sources
  lineinfile:
    path: /etc/apt/sources.list.d/docker.list
    line: "deb [arch={{ deb_architecture.stdout }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
    create: yes
  when: ansible_distribution == "Debian"

- name: Update Apt cache
  apt:
    update_cache: yes
